api = "0.2"

[buildpack]
  id = "org.cloudfoundry.bundler"
  name = "Bundler Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "b7502506bb8ab5312d4efa208d39dca4a5830762ba6b4b094a72e9aa69702341"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler-1.17.3-any-stack-b7502506.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "dd5d424bc5af910899059545b997b85cd8e164331985965ee2f6de8e6233e1ca"
    source = "https://github.com/bundler/bundler/tree/v2.1.1"
    source_sha256 = "c20e3e7a18de9d99b5919eaaee4dbeecc55ffcbfd08e1807572a618f426fdfc2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler-2.1.1-any-stack-dd5d424b.tgz"
    version = "2.1.1"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "61a9123c9dd5bd1cebd7a74ee4cfaa13b06ba8604385beb313f325e91f03c8a0"
    source = "https://github.com/bundler/bundler/tree/v2.1.2"
    source_sha256 = "a3d89c9a7fbfe9364512cac10bc8dc4f9c370e41375c03cd36cad31eef6fb961"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler-2.1.2-any-stack-61a9123c.tgz"
    version = "2.1.2"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
